server:
  port: 8084

spring:
  application:
    name: job-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

xxl:
  job:
    admin:
      addresses: http://localhost:8089/xxl-job-admin
    executor:
      appname: job-service
      address: 'http://localhost:8084'
      log-path: '/data/applogs/xxl-job/jobhandler'
      logretentiondays: 30
      ip: '0.0.0.0'
      port: 9999
    accessToken: '4221ac56ab466a4efb7b556dc1556b9d'

xxl-job:
  schedule:
    orderTimeoutJob: 0 * * * * ?  # 每分钟执行一次