server:
  port: 8085

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: job
          uri: lb://job-service
          predicates:
            - Path=/job/**
        - id: seckill_start
          uri: lb://product-service
          predicates:
            - Path=/api/seckill/start/{productId}